
-- Reset sequences after inserting manual IDs (for H2 Database)
ALTER TABLE guest ALTER COLUMN id RESTART WITH 21;
ALTER TABLE room ALTER COLUMN id RESTART WITH 21;
ALTER TABLE room_type ALTER COLUMN id RESTART WITH 6;
ALTER TABLE amenity ALTER COLUMN id RESTART WITH 21;
ALTER TABLE reservation ALTER COLUMN id RESTART WITH 21;
ALTER TABLE reservation_room ALTER COLUMN id RESTART WITH 21;
ALTER TABLE service ALTER COLUMN id RESTART WITH 11;
ALTER TABLE service_request ALTER COLUMN id RESTART WITH 11;
ALTER TABLE invoice ALTER COLUMN id RESTART WITH 7;
ALTER TABLE payment ALTER COLUMN id RESTART WITH 6;
